// Generated by https://quicktype.io

export interface IDashboardSummaryResponse {
  numberOfOrders: number;
  paidOrders: number;
  notPaidOrders: number;
  numberOfClients: number;
  numberOfUsers: number;
  numberOfProducts: number;
  productsWithNoInventory: number;
  lowInventory: number;
}
