// Generated by https://quicktype.io

export interface FetchProducts {
  ok: boolean;
  products: Product[];
}

export interface Product {
  images: string[];
  inStock: number;
  price: number;
  slug: string;
  title: string;
}
